# fly.toml app configuration file generated for retransapp on 2023-06-11T11:52:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "retransapp"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "fra"

[env]

[experimental]
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[processes]
  worker = "python3 app.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# fly.toml app configuration file generated for throbbing-brook-9747 on 2023-06-12T08:04:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# app = "throbbing-brook-9747"
# primary_region = "arn"
#
# [http_service]
#   internal_port = 8000
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
