# fly.toml app configuration file generated for retransapp on 2023-06-11T11:52:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "retransapp"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[processes]
  app = "retransapp"
  worker = "python3 app.py"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
